CREATE OR REPLACE FUNCTION Store_Card_Key(_CardKey text) RETURNS BIGINT AS $BODY$
DECLARE
_CardID bigint;
BEGIN
INSERT INTO Cards (CardKey) VALUES (_CardKey) RETURNING CardID INTO STRICT _CardID;
RETURN _CardID;
END;
$BODY$ LANGUAGE plpgsql VOLATILE SECURITY DEFINER;
