CREATE OR REPLACE FUNCTION Store_Card_Key(_CardHash text, _CardKey text) RETURNS BIGINT AS $BODY$
DECLARE
_CardID bigint;
BEGIN
INSERT INTO Cards (CardHash, CardKey) VALUES (_CardHash, _CardKey) RETURNING CardID INTO STRICT _CardID;
RETURN _CardID;
END;
$BODY$ LANGUAGE plpgsql VOLATILE SECURITY DEFINER;
